import type { Metadata } from "next";
import { Inter, Oxygen } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });
const oxygem = Oxygen({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-Br">
      <body className={cn(oxygem.className, "min-h-screen flex flex-col")}>
        <Header />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
